server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 610555
    url: jdbc:mysql://localhost:3306/film_comment_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# 文件上传的前缀url
fileBaseUrl: http://localhost:9090

#SpringDoc OpenAPI配置
#Swagger UI 访问路径： http://localhost:9090/swagger-ui.html
springdoc:
  swagger-ui:
    #启用 Swagger UI 页面。
    enabled: true
    #设置访问 Swagger UI 的页面路径
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs
packages-to-scan: com.example.controller # 指定扫描包路径

#Oss配置
aliyun:
   oss:
     file:
       endpoint: oss-cn-beijing.aliyuncs.com
       keyid: LTAI5tKM9N9AfFLdkDoAUyzZ
       keysecret: UYFSsTfVIEUK6pbXezwPQlKLwsZvUU
       bucketname: film-comment-system
